
# note that this requires the python path to be set appropriately, and hence this
# should be invoked by calling the windows-exe taget in the top level makefile

windows-exe:
	$(PYTHON) setup.py py2exe

