sudo: false
language: python
cache: pip
dist: xenial
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
git:
  depth: 1000

env:
  global:
    - TAHOE_LAFS_HYPOTHESIS_PROFILE=ci

install:
  - pip install --upgrade tox setuptools virtualenv
  - echo $PATH; which python; which pip; which tox
  - python misc/build_helpers/show-tool-versions.py

script:
  - |
    set -eo pipefail
    # Only bother to exercise tests that we strongly believe will pass under
    # Python 3. After all, who wants bad news? First we need to create the tox
    # env, though, so we can use it to list the modules we want to test ...
    tox -e ${T} --notest
    tox -e ${T} $(.tox/${T}/bin/python -c 'from allmydata.util._python3 import PORTED_TEST_MODULES; print(" ".join(PORTED_TEST_MODULES))')

notifications:
  email: false
  irc:
    channels: "chat.freenode.net#tahoe-lafs"
    on_success: always # for testing
    on_failure: always
    template:
      - "%{repository}#%{build_number} [%{branch}: %{commit} by %{author}] %{message}"
      - "Changes: %{compare_url} | Details: %{build_url}"

matrix:
  include:
  - os: linux
    python: '3.6'
    env: T=py36

  fast_finish: true
