sudo: true
os:
 - "linux"
 - "osx"
# xcode7 gives us OS-X 10.10, which gives us newer OpenSSL (the default gives
# us 10.9, which appears to have OpenSSL-0.9.8, which is rejected by
# cryptography-1.4)
osx_image: xcode7
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
python:
  - "2.7"
  - "pypy"
before_install:
  - sh -c set
  - git config --global user.email "travis-tahoe@tahoe-lafs.org"
  - git config --global user.name "Travis Tahoe"
  - git fetch --depth=1000
  - python misc/build_helpers/show-tool-versions.py
install:
#  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update && brew install python; fi
  - hash -r
  - echo $PATH; which python; which pip; python --version
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then wget https://bootstrap.pypa.io/get-pip.py && sudo python ./get-pip.py; fi
  - pip --version
  - pip list
  - pip install --user coveralls tox wheel
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=$HOME/Library/Python/2.7/bin:$PATH; fi
  - echo $PATH; which python; which pip; which tox
  - python misc/build_helpers/show-tool-versions.py
script:
  - echo $PATH; which python; which pip; which tox
  - tox -e coverage
after_success:
  coveralls
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#tahoe-lafs"
    on_success: always # for testing
    on_failure: always
    template:
      - "%{repository}#%{build_number} [%{branch}: %{commit} by %{author}] %{message}"
      - "Changes: %{compare_url} | Details: %{build_url}"
matrix:
  allow_failures:
    - python: "pypy"
  fast_finish: true
