FROM python:3

LABEL maintainer "gordon@leastauthority.com"

RUN git clone https://github.com/tahoe-lafs/tahoe-lafs.git /root/tahoe-lafs && \
    cd /root/tahoe-lafs && \
    pip install --editable . && \
    tahoe --version

RUN cd /root && \
    mkdir .tahoe-client .tahoe-introducer .tahoe-server

RUN tahoe create-introducer --location=tcp:introducer:3458 --port=tcp:3458 /root/.tahoe-introducer
RUN timeout 4 tahoe run /root/.tahoe-introducer || true
RUN tahoe create-node --location=tcp:server:3457 --port=tcp:3457 --introducer=$(cat /root/.tahoe-introducer/private/introducer.furl) /root/.tahoe-server
RUN tahoe create-client --webport=3456 --introducer=$(cat /root/.tahoe-introducer/private/introducer.furl) --basedir=/root/.tahoe-client --shares-needed=1 --shares-happy=1 --shares-total=1

VOLUME ["/root/.tahoe-client", "/root/.tahoe-server", "/root/.tahoe-introducer"]
EXPOSE 3456 3457 3458
ENTRYPOINT ["tahoe"]
CMD []
