FROM debian:8

RUN apt-get --quiet update && \
    apt-get --quiet --yes install git && \
    apt-get --quiet --yes install \
        sudo \
    	build-essential \
	python2.7 \
    	python2.7-dev \
    	libffi-dev \
    	libssl-dev \
    	libyaml-dev \
    	virtualenv
