#!/usr/bin/env python

# This is a munin plugin which pulls data from the server in
# misc/operations_helpers/spacetime/diskwatcher.tac . It produces a graph of how much space is
# used on all disks across the grid. The plugin should be configured with
# env_url= pointing at the diskwatcher.tac webport.

import os, sys, urllib, simplejson

if len(sys.argv) > 1 and sys.argv[1] == "config":
    print """\
graph_title Tahoe Total Disk Space Used
graph_vlabel bytes used
graph_category tahoe
graph_info This graph shows the total amount of disk space used across the grid
disk_used.label disk used
disk_used.draw LINE1"""
    sys.exit(0)

url = os.environ["url"]
data = simplejson.load(urllib.urlopen(url))["used"]
print "disk_used.value", data
