#!/bin/bash

if [ -d /Applications/tahoe.app ]; then
    rm -r /Applications/tahoe.app
fi

if [ -f /etc/paths.d/tahoe ]; then
    rm /etc/paths.d/tahoe
fi

if [ -f /etc/manpaths.d/tahoe.1 ]; then
    rm /etc/manpaths.d/tahoe.1
fi