name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:

  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
        python-version:
          - 2.7

    steps:

      # Get vcpython27 on Windows + Python 2.7, to build netifaces
      # extension.  See https://chocolatey.org/packages/vcpython27 and
      # https://github.com/crazy-max/ghaction-chocolatey
      - name: Install MSVC 9.0 for Python 2.7 [Windows]
        if: matrix.os == 'windows-latest' && matrix.python-version == '2.7'
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install vcpython27

      # See https://github.com/actions/checkout. A fetch-depth of 0
      # fetches all tags and branches.
      - name: Check out Tahoe-LAFS sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      # To use pip caching with GitHub Actions in an OS-independent
      # manner, we need `pip cache dir` command, which became
      # available since pip v20.1+.  At the time of writing this,
      # GitHub Actions offers pip v20.3.3 for both ubuntu-latest and
      # windows-latest, and pip v20.3.1 for macos-latest.
      - name: Get pip cache directory
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      # See https://github.com/actions/cache
      - name: Use pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python packages
        run: |
          pip install --upgrade codecov tox setuptools
          pip list

      - name: Display tool versions
        run: python misc/build_helpers/show-tool-versions.py

      - name: Run "tox -e py27-coverage"
        run: tox -e py27-coverage

      - name: Upload eliot.log in case of failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: eliot.log
          path: eliot.log

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: abf679b6-e2e6-4b33-b7b5-6cfbd41ee691
          file: coverage.xml
